services:
    postgres:
        image: postgres
        environment: 
            - POSTGRES_PASSWORD=admin
        ports:
            -  5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
    mongo:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=admin 
        ports:
            - 27017:27017
        volumes:
            - mongodata://var/lib/mongodb/data
volumes:
    pgdata:
    mongodata: