services:
    postgres:
        image: postgres
        environment: 
            - POSTGRES_PASSWORD=admin
        ports:
            -  5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
    mongo:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=admin 
        ports:
            - 27017:27017
        volumes:
            - mongodata://var/lib/mongodb/data
    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports: 
            - 5672:5672
            - 15672:15672
    auction-svc:
        image: nielbesen/auction-svc:latest
        build:
            context: .
            dockerfile: AuctionService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URL=http://+:8080
            - RabbitMq__Host=rabbitmq
            - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=admin;Database=auctions
            - IdentityServiceUrl=http://identity-svc
        ports:
            - 7001:8080
        depends_on:
            - postgres
            - rabbitmq 
    search-svc:
        image: nielbesen/search-svc:latest
        build:
            context: .
            dockerfile: SearchService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URL=http://+:8080
            - RabbitMq__Host=rabbitmq
            - ConnectionStrings__MongoDbConnection=mongodb://root:admin@mongo
            - AuctionServiceUrl=http://auction-svc
        ports:
            - 7002:8080
        depends_on:
            - mongo
            - rabbitmq 
    identity-svc:
        image: nielbesen/identity-svc:latest
        build:
            context: .
            dockerfile: IdentityService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URL=http://+:8080
            - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=admin;Database=identity
        ports:
            - 5000:8080
        depends_on:
            - postgres
    gateway-svc:
        image: nielbesen/gateway-svc:latest
        build:
            context: .
            dockerfile: GatewayService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
            - ASPNETCORE_URL=http://+:8080
        ports:
            - 6001:8080
        depends_on:
            - postgres
volumes:
    pgdata:
    mongodata: